// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm4rbllqmyHgEScflCIZTBYnzNoeld6Lk',
    appId: '1:663678880544:web:848a74f5d89bca5aae6545',
    messagingSenderId: '663678880544',
    projectId: 'women-safety-app-dff14',
    authDomain: 'women-safety-app-dff14.firebaseapp.com',
    storageBucket: 'women-safety-app-dff14.appspot.com',
    measurementId: 'G-J24TJDEHR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3XTd56QYqXMIQO1UX-edntxyFb4fKmrM',
    appId: '1:663678880544:android:f3730ac89b80e78cae6545',
    messagingSenderId: '663678880544',
    projectId: 'women-safety-app-dff14',
    storageBucket: 'women-safety-app-dff14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVPCjT_NC3a84Q4deNOfNoEPeR9oJ2bUQ',
    appId: '1:663678880544:ios:138098c86c34be55ae6545',
    messagingSenderId: '663678880544',
    projectId: 'women-safety-app-dff14',
    storageBucket: 'women-safety-app-dff14.appspot.com',
    iosBundleId: 'com.example.womenSafteyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVPCjT_NC3a84Q4deNOfNoEPeR9oJ2bUQ',
    appId: '1:663678880544:ios:eb78906e74f8b3d5ae6545',
    messagingSenderId: '663678880544',
    projectId: 'women-safety-app-dff14',
    storageBucket: 'women-safety-app-dff14.appspot.com',
    iosBundleId: 'com.example.womenSafteyApp.RunnerTests',
  );
}
